const express=reqiure('express')
const restaurents=express.Routes()
restaurents.get('signIn',)
restaurents.post('signUp',)
restaurents.use('signOut',)
restaurents.use('reservation',)
restaurents.use('search',)
restaurents.use('history',)
restaurents.use('profile',)
restaurents.use('userObject',)