const express = require('express')
const {signin_restaurent,signup_restaurent}=require('../controllers/restaurents/index')
const restaurents= express.Router()
restaurents.post('signIn',signin_restaurent)
restaurents.post('signUp',signup_restaurent)
// restaurents.use('signOut',)
// restaurents.use('reservation',)
// restaurents.use('search',)
// restaurents.use('history',)
// restaurents.use('profile',)
// restaurents.use('userObject',)