const express=reqiure('express')
const user=express.Routes()
user.get('signIn',)
user.post('signUp',)
user.use('signOut',)
user.post('reservation',)
user.get('search',)
user.use('history',)
user.use('userObject',)