const express=require('express')
const user=express.Router()
user.post('signIn',)
user.post('signUp',)
user.use('signOut',)
user.post('reservation',)
user.get('search',)
user.use('history',)
user.use('userObject',)